use_frameworks!

platform :ios, '11.0'

target 'SkyWayVideoCall_Example' do
  pod 'SkyWayVideoCall', :git => 'https://github.com/nuwaithu24/SkyWayVideoCall'

  target 'SkyWayVideoCall_Tests' do
    inherit! :search_paths

    
  end
end
